### ISSUE TITLE
An Error Was Encountered code : 404

### ISSUE THREAD

**Issue by Nassreddin** [Blair2004/nexopos-4#68]
Hi my friend
great work like always 

http://prntscr.com/iqle28
when you click on edit btn
this happens
http://prntscr.com/iqletm
the link is : 
64.15.133.96/nexopos/dashboard/nexo/produits/lists/edit/1 ( not working )

it's not a big issue , sense we can edit the product from the dashbord .
link to same item:
64.15.133.96/nexopos/dashboard/stores/2/nexo/items/edit/1 ( works )

**Comment by Blair2004** [comment]
Hi, for submitting issue about NexoPOS 3.x, please contact us at contact@nexopos.com
